package app.mmmap.ui.theme

import androidx.compose.ui.graphics.Color

// Brand / distinction colours — used by the map layer and badge labels
val MichelinRed  = Color(0xFFE2001A)
val StarGold     = Color(0xFFFFB400)
val TwoStarViolet = Color(0xFF7B1FA2)
val OneStarCyan  = Color(0xFF00BCD4)
val BibGreen     = Color(0xFF00AA66)
val BibBrown     = Color(0xFF8B4513)
val SelectedBlue = Color(0xFF1565C0)
val GreenStar    = Color(0xFF2E7D32)
val UserGrey     = Color(0xFF9E9E9E)

// ── Light colour scheme (brand-tuned, generated from MichelinRed as seed) ─────
val md_light_primary             = MichelinRed
val md_light_onPrimary           = Color(0xFFFFFFFF)
val md_light_primaryContainer    = Color(0xFFFFDAD6)
val md_light_onPrimaryContainer  = Color(0xFF410002)
val md_light_secondary           = Color(0xFF775652)
val md_light_onSecondary         = Color(0xFFFFFFFF)
val md_light_secondaryContainer  = Color(0xFFFFDAD6)
val md_light_onSecondaryContainer= Color(0xFF2C1512)
val md_light_tertiary            = Color(0xFF755B2F)
val md_light_onTertiary          = Color(0xFFFFFFFF)
val md_light_tertiaryContainer   = Color(0xFFFFDEA8)
val md_light_onTertiaryContainer = Color(0xFF271900)
val md_light_error               = Color(0xFFBA1A1A)
val md_light_onError             = Color(0xFFFFFFFF)
val md_light_errorContainer      = Color(0xFFFFDAD6)
val md_light_onErrorContainer    = Color(0xFF410002)
val md_light_background          = Color(0xFFFFFBFF)
val md_light_onBackground        = Color(0xFF201A19)
val md_light_surface             = Color(0xFFFFFBFF)
val md_light_onSurface           = Color(0xFF201A19)
val md_light_surfaceVariant      = Color(0xFFF5DDDA)
val md_light_onSurfaceVariant    = Color(0xFF534341)
val md_light_outline             = Color(0xFF857370)
val md_light_outlineVariant      = Color(0xFFD8C2BF)
val md_light_scrim               = Color(0xFF000000)
val md_light_inverseSurface      = Color(0xFF362F2E)
val md_light_inverseOnSurface    = Color(0xFFFBEEEC)
val md_light_inversePrimary      = Color(0xFFFFB4AB)

// ── Dark colour scheme ─────────────────────────────────────────────────────────
val md_dark_primary              = Color(0xFFFFB4AB)
val md_dark_onPrimary            = Color(0xFF690005)
val md_dark_primaryContainer     = Color(0xFF93000A)
val md_dark_onPrimaryContainer   = Color(0xFFFFDAD6)
val md_dark_secondary            = Color(0xFFE7BDBA)
val md_dark_onSecondary          = Color(0xFF442927)
val md_dark_secondaryContainer   = Color(0xFF5D3F3C)
val md_dark_onSecondaryContainer = Color(0xFFFFDAD6)
val md_dark_tertiary             = Color(0xFFE5C27E)
val md_dark_onTertiary           = Color(0xFF402D05)
val md_dark_tertiaryContainer    = Color(0xFF5A4319)
val md_dark_onTertiaryContainer  = Color(0xFFFFDEA8)
val md_dark_error                = Color(0xFFFFB4AB)
val md_dark_onError              = Color(0xFF690005)
val md_dark_errorContainer       = Color(0xFF93000A)
val md_dark_onErrorContainer     = Color(0xFFFFDAD6)
val md_dark_background           = Color(0xFF201A19)
val md_dark_onBackground         = Color(0xFFEDE0DE)
val md_dark_surface              = Color(0xFF201A19)
val md_dark_onSurface            = Color(0xFFEDE0DE)
val md_dark_surfaceVariant       = Color(0xFF534341)
val md_dark_onSurfaceVariant     = Color(0xFFD8C2BF)
val md_dark_outline              = Color(0xFFA08C89)
val md_dark_outlineVariant       = Color(0xFF534341)
val md_dark_scrim                = Color(0xFF000000)
val md_dark_inverseSurface       = Color(0xFFEDE0DE)
val md_dark_inverseOnSurface     = Color(0xFF201A19)
val md_dark_inversePrimary       = MichelinRed
