#!/usr/bin/env python3
"""
Generates app/src/main/assets/michelin.db.seed from the upstream CSV.

The asset is gzipped: the raw SQLite file is ~19 MB and ships uncompressed in every
APK, whereas gzipped it is ~7 MB. DatabaseModule inflates it via
Room.createFromInputStream on first open.

Also records the upstream CSV blob SHA into
app/src/main/res/values/dataset_provenance.xml. MmmapApplication seeds that value
into SyncPreferences on first launch, so the first DatasetSyncWorker run is a no-op
unless upstream has actually moved — otherwise every fresh install re-downloads the
whole 17.5 MB CSV to rebuild data it already shipped with.

The produced SQLite file matches the Room v2 schema (AppDatabase version = 2):
  - restaurant      (RestaurantEntity)
  - foursquare_cache (FoursquareCacheEntity, empty)
  - visited_restaurant (VisitedRestaurantEntity, empty)

user_version pragma is set to 2 so Room skips migrations on first open.
room_master_table is intentionally omitted — Room creates it on first open.

Usage:
    python3 scripts/seed_db.py [--out app/src/main/assets/michelin.db.seed]
    or via:
    just seed-db
"""

import argparse
import csv
import gzip
import hashlib
import io
import json
import shutil
import sqlite3
import sys
import tempfile
import urllib.request
from pathlib import Path

CSV_URL = (
    "https://raw.githubusercontent.com/ngshiheng/michelin-my-maps"
    "/main/data/michelin_my_maps.csv"
)

# Same blob DatasetSyncWorker polls for its change check.
CSV_CONTENTS_API = (
    "https://api.github.com/repos/ngshiheng/michelin-my-maps"
    "/contents/data/michelin_my_maps.csv"
)

PROVENANCE_XML = "app/src/main/res/values/dataset_provenance.xml"

# Column indices in the upstream CSV (0-indexed, skip header row)
# 0:Name 1:Address 2:Location 3:Price 4:Cuisine 5:Longitude 6:Latitude
# 7:PhoneNumber 8:Url 9:WebsiteUrl 10:Award 11:GreenStar 12:FacilitiesAndServices 13:Description

DDL_RESTAURANT = """
CREATE TABLE IF NOT EXISTS `restaurant` (
    `id` TEXT NOT NULL,
    `name` TEXT NOT NULL,
    `address` TEXT NOT NULL,
    `location` TEXT,
    `latitude` REAL NOT NULL,
    `longitude` REAL NOT NULL,
    `award` TEXT,
    `greenStar` INTEGER NOT NULL,
    `cuisine` TEXT,
    `price` TEXT,
    `phoneNumber` TEXT,
    `url` TEXT NOT NULL,
    `websiteUrl` TEXT,
    `description` TEXT,
    `facilitiesAndServices` TEXT,
    PRIMARY KEY(`id`)
);
"""

DDL_FOURSQUARE_CACHE = """
CREATE TABLE IF NOT EXISTS `foursquare_cache` (
    `restaurantId` TEXT NOT NULL,
    `fsqId` TEXT,
    `photoUrl` TEXT,
    `openingHoursJson` TEXT,
    `phone` TEXT,
    `rating` REAL,
    `fetchedAt` INTEGER NOT NULL,
    PRIMARY KEY(`restaurantId`)
);
"""

# Matches MIGRATION_1_2 SQL exactly
DDL_VISITED = """
CREATE TABLE IF NOT EXISTS visited_restaurant (
    restaurant_id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    latitude REAL NOT NULL,
    longitude REAL NOT NULL,
    award TEXT,
    cuisine TEXT,
    visited_at INTEGER NOT NULL
);
"""


def sha256_prefix(text: str) -> str:
    """Mirrors DatasetSyncWorker.sha256Prefix — first 16 hex chars of SHA-256."""
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
    return digest[:16]


def nonempty(s: str) -> str | None:
    v = s.strip()
    return v if v else None


def price(s: str) -> str | None:
    """Normalise the price band, dropping the literal "none" the upstream CSV uses.

    Price tiers are derived at query time as LENGTH(price), and LENGTH("none") is 4 —
    which would file those rows under the most expensive tier alongside "$$$$".
    Mirrors DatasetSyncWorker.normalisePrice.
    """
    v = s.strip()
    return None if not v or v.lower() == "none" else v


def fetch_csv_sha(url: str) -> str:
    """Blob SHA of the upstream CSV, as reported by the GitHub Contents API."""
    print(f"Fetching CSV blob SHA from {url} …", file=sys.stderr)
    req = urllib.request.Request(url, headers={"Accept": "application/vnd.github+json"})
    with urllib.request.urlopen(req) as resp:
        sha = json.load(resp)["sha"]
    print(f"  sha = {sha}", file=sys.stderr)
    return sha


def write_provenance(sha: str, path: Path) -> None:
    """Record the seeded CSV's SHA as a string resource.

    Committed rather than fetched at build time: a network call during the build
    would break F-Droid's reproducible-build verification.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by scripts/seed_db.py — do not edit by hand. -->\n"
        "<resources>\n"
        f'    <string name="bundled_csv_sha" translatable="false">{sha}</string>\n'
        "</resources>\n"
    )
    print(f"Wrote provenance → {path}", file=sys.stderr)


def download_csv(url: str) -> list[list[str]]:
    print(f"Downloading CSV from {url} …", file=sys.stderr)
    with urllib.request.urlopen(url) as resp:
        content = resp.read().decode("utf-8")
    reader = csv.reader(io.StringIO(content))
    rows = list(reader)
    print(f"  {len(rows) - 1} data rows (excl. header)", file=sys.stderr)
    return rows


def parse_rows(rows: list[list[str]]) -> list[tuple]:
    entities = []
    for row in rows[1:]:  # skip header
        if len(row) < 13:
            continue
        url = nonempty(row[8])
        if not url:
            continue
        try:
            lat = float(row[6])
            lon = float(row[5])
        except ValueError:
            continue
        green_star = 1 if row[11].strip().lower() == "true" else 0
        description = nonempty(row[13]) if len(row) > 13 else None
        entities.append((
            sha256_prefix(url),  # id
            row[0].strip(),       # name
            row[1].strip(),       # address
            nonempty(row[2]),     # location
            lat,                  # latitude
            lon,                  # longitude
            nonempty(row[10]),    # award
            green_star,           # greenStar
            nonempty(row[4]),     # cuisine
            price(row[3]),        # price
            nonempty(row[7]),     # phoneNumber
            url,                  # url
            nonempty(row[9]),     # websiteUrl
            description,          # description
            nonempty(row[12]),    # facilitiesAndServices
        ))
    return entities


def build_db(out_path: Path, rows: list[list[str]]) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    if out_path.exists():
        out_path.unlink()

    conn = sqlite3.connect(str(out_path))
    try:
        cur = conn.cursor()
        cur.executescript(DDL_RESTAURANT + DDL_FOURSQUARE_CACHE + DDL_VISITED)

        entities = parse_rows(rows)
        cur.executemany(
            """INSERT OR REPLACE INTO restaurant VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
            entities,
        )
        conn.commit()

        # Set schema version to 2 so Room skips migrations on first open.
        # Must be done outside a transaction (PRAGMA user_version is not transactional).
        cur.execute("PRAGMA user_version = 2")
        conn.commit()

        cur.execute("SELECT COUNT(*) FROM restaurant")
        count = cur.fetchone()[0]
        print(f"Wrote {count} rows → {out_path}", file=sys.stderr)
        if count < 100:
            print("ERROR: suspiciously few rows — aborting", file=sys.stderr)
            sys.exit(1)
    finally:
        conn.close()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        default="app/src/main/assets/michelin.db.seed",
        help="Output path for the gzipped SQLite asset",
    )
    args = parser.parse_args()

    out = Path(args.out)
    sha = fetch_csv_sha(CSV_CONTENTS_API)
    rows = download_csv(CSV_URL)

    # Build uncompressed to a temp file, then gzip into place. mtime=0 keeps the
    # gzip header byte-identical across runs for the same input, which matters for
    # F-Droid's reproducible-build check.
    with tempfile.TemporaryDirectory() as tmp:
        raw = Path(tmp) / "michelin.db"
        build_db(raw, rows)
        out.parent.mkdir(parents=True, exist_ok=True)
        # The output handle is opened separately and closed explicitly: GzipFile only
        # closes a fileobj it opened itself, so passing open(...) inline would leave the
        # trailer flush depending on refcount collection.
        with open(raw, "rb") as src, open(out, "wb") as out_fh:
            with gzip.GzipFile(filename="", mode="wb", fileobj=out_fh, mtime=0) as dst:
                shutil.copyfileobj(src, dst)
        raw_mb = raw.stat().st_size / 1048576
        gz_mb = out.stat().st_size / 1048576
        print(
            f"Gzipped {raw_mb:.1f} MB → {gz_mb:.1f} MB ({out})",
            file=sys.stderr,
        )

    write_provenance(sha, Path(PROVENANCE_XML))

    # The stale uncompressed asset would otherwise keep bloating the APK.
    legacy = out.parent / "michelin.db"
    if legacy.exists():
        legacy.unlink()
        print(f"Removed legacy {legacy}", file=sys.stderr)


if __name__ == "__main__":
    main()
